package buku;


import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class nouveauLivre extends javax.swing.JFrame {

    /**
     * Creates new form nouveauLivre
     */
    public nouveauLivre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        isbnT = new javax.swing.JTextField();
        coteT = new javax.swing.JTextField();
        titreT = new javax.swing.JTextField();
        auteurT = new javax.swing.JTextField();
        maisonEditionT = new javax.swing.JTextField();
        anneeT = new javax.swing.JTextField();
        domaineT = new javax.swing.JTextField();
        motsClesT = new javax.swing.JTextField();
        annulerT = new javax.swing.JButton();
        enregistrerT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ENREGISTREMENT DES LIVRES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 710, 80));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ISBN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 110, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("COTE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 90, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TITRE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 100, 30));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AUTEUR");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 90, 30));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MAISON D'EDITION");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 180, 40));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ANNEE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 110, 30));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DOMAINE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 140, 30));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MOTS CLES");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 130, 30));

        isbnT.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jPanel1.add(isbnT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 180, 30));

        coteT.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        coteT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coteTActionPerformed(evt);
            }
        });
        jPanel1.add(coteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 180, 30));

        titreT.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        titreT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titreTActionPerformed(evt);
            }
        });
        jPanel1.add(titreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 180, 30));

        auteurT.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        auteurT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auteurTActionPerformed(evt);
            }
        });
        jPanel1.add(auteurT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 180, 30));

        maisonEditionT.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jPanel1.add(maisonEditionT, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 190, 30));

        anneeT.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        anneeT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anneeTActionPerformed(evt);
            }
        });
        jPanel1.add(anneeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 190, 30));

        domaineT.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        domaineT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domaineTActionPerformed(evt);
            }
        });
        jPanel1.add(domaineT, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 190, 30));

        motsClesT.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jPanel1.add(motsClesT, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 200, 30));

        annulerT.setText("ANNULER");
        annulerT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerTActionPerformed(evt);
            }
        });
        jPanel1.add(annulerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 150, 40));

        enregistrerT.setBackground(new java.awt.Color(0, 51, 204));
        enregistrerT.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        enregistrerT.setText("ENREGISTRER");
        enregistrerT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerTActionPerformed(evt);
            }
        });
        jPanel1.add(enregistrerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 190, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_home_64px_2.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 60, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1110, 700));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 204, 204,80));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/bck.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1110, 700));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_about_32px_1.png"))); // NOI18N
        jLabel24.setText("A PROPOS");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 200, 40));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_exit_32px_1.png"))); // NOI18N
        jLabel23.setText("DECONNECTER");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 220, 30));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_shortlist_32px_1.png"))); // NOI18N
        jLabel21.setText("REGISTRE JOURNALIER");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 230, 30));

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_literature_32px_2.png"))); // NOI18N
        jLabel20.setText("REPERTOIRE LIVRES");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 220, 30));

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_send_hot_list_32px_3.png"))); // NOI18N
        jLabel22.setText("LISTE ABONNES");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 220, 30));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_add_male_user_32px.png"))); // NOI18N
        jLabel19.setText("AJOUTER UN ABONNE");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 220, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_calendar_32px.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 40, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_administrator_male_32px.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 40));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 30));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void domaineTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domaineTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domaineTActionPerformed

    private void anneeTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anneeTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anneeTActionPerformed

    private void coteTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coteTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coteTActionPerformed

    private void titreTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titreTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titreTActionPerformed

    private void auteurTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auteurTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auteurTActionPerformed

    private void annulerTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerTActionPerformed
        
         isbnT.setText("");
         coteT.setText("");
         titreT.setText("");
         auteurT.setText("");
         maisonEditionT.setText("");
         anneeT.setText("");
         domaineT.setText("");
         motsClesT.setText("");
    }//GEN-LAST:event_annulerTActionPerformed

    private void enregistrerTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerTActionPerformed
        try{
            String Status = "in"; 
            Connection MyCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/buku", "root","14400000");
            Statement MyStmt = MyCon.createStatement();
            String ISBN=isbnT.getText();
            String Cote= coteT.getText();
            String Titre=titreT.getText();
            String Auteur= auteurT.getText();
            String MEdition=maisonEditionT.getText();
            String annee=anneeT.getText();
            String Domaine=domaineT.getText();
            String MotsCles=motsClesT.getText();
            
            
            if( ISBN.isEmpty() || Cote.isEmpty() || Titre.isEmpty()||Auteur.isEmpty() ||MEdition.isEmpty() ||annee.isEmpty()||Domaine.isEmpty()||MotsCles.isEmpty() )
        {
            
            JOptionPane.showMessageDialog(null,"Remplissez tous les champs","Attention",JOptionPane.PLAIN_MESSAGE);
        }
            
        else{
          
            String sql;
                sql = "Insert into books"
                        +"(ISBN, Cote, Titre, Auteur, Publication, Annee, Domain, Status, motsClefs)"
                        + String.format("values('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s')", ISBN, Cote, Titre, Auteur, MEdition, annee, Domaine, Status, MotsCles);
                    MyStmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Operation reussie!(^-^)","",JOptionPane.PLAIN_MESSAGE);
        }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        
        
    }//GEN-LAST:event_enregistrerTActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new repertoire().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        new FormulaireInscription().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        new ImproveListe().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        new repertoire().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        new Registre().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nouveauLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nouveauLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nouveauLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nouveauLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nouveauLivre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anneeT;
    private javax.swing.JButton annulerT;
    private javax.swing.JTextField auteurT;
    private javax.swing.JTextField coteT;
    private javax.swing.JTextField domaineT;
    private javax.swing.JButton enregistrerT;
    private javax.swing.JTextField isbnT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField maisonEditionT;
    private javax.swing.JTextField motsClesT;
    private javax.swing.JTextField titreT;
    // End of variables declaration//GEN-END:variables
}
