
package buku;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DZATECH
 */
public class repertoire extends javax.swing.JFrame {
    public static ResultSet  myRs;
    public static Statement Stmt, myStmt;
    

    public repertoire() {
        initComponents();
        
        jTable1.getTableHeader().setBackground(new Color(0,102,255));
         jTable1.getTableHeader().setFont(new Font("Sergoe UI",Font.BOLD, 14));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setForeground(new Color(32,136,203));
        jTable1.setRowHeight(25);
        
        try{
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            
            Connection Conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/buku", "root", "14400000");
             Stmt = Conn.createStatement();
            while(model.getRowCount()>0){
                 model.removeRow(0);
             }
        
                  ResultSet  Rs = Stmt.executeQuery("select ISBN, Cote, Titre, Auteur, Publication, Annee, Domain, Status from books");
                  
                      
                            while(Rs.next()) {
                              //affichage be la base de donnees dans le tableaux
                              model.insertRow(model.getRowCount(), new Object[]{Rs.getString("ISBN"), Rs.getString("Cote"), Rs.getString("Titre"), Rs.getString("Auteur"), Rs.getString("Publication"), Rs.getString("Annee"),Rs.getString("Domain"), Rs.getString("Status")});
				   /*System.out.println(myRs.getString("Id")+ " "+ myRs.getString("first_name") + " " + myRs.getString("last_name")+" "+ myRs.getString("email"));*/
				   
			   }
            
                            
                        
			//4.process the result set
			  
            
        }catch(Exception exc){
            exc.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "COTE", "TITRE", "AUTEUR", "PUBLICATION", "ANNEE", "DOMAINE", "STATUS"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(0, 102, 255));
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 1060, 300));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  FILTRER PAR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, 40));

        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ISBN", "COTE", "TITRE", "PUBLICATION", "ANNEE","AUTEUR", "DOMAINE", "STATUS" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, 40));

        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 330, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("RECHERCHER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 140, 40));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Repertoire des livres");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 710, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_go_back_64px_1.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 60));

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("AJOUTER UN LIVRE");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 180, 40));

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton4.setText("Mouvement Livre");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 640, 240, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1100, 700));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/bck.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1100, 710));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_add_male_user_32px.png"))); // NOI18N
        jLabel19.setText("AJOUTER UN ABONNE");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_send_hot_list_32px_3.png"))); // NOI18N
        jLabel22.setText("LISTE ABONNES");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_shortlist_32px_1.png"))); // NOI18N
        jLabel21.setText("REGISTRE JOURNALIER");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_administrator_male_32px.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 80, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_calendar_32px.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 80, -1, -1));

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_literature_32px_2.png"))); // NOI18N
        jLabel20.setText("REPERTOIRE LIVRES");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_administrator_male_32px.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 40, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_calendar_32px.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 30));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, 30));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_about_32px.png"))); // NOI18N
        jLabel9.setText("    A PROPOS");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 160, 30));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buku/Icons/icons8_exit_32px_1.png"))); // NOI18N
        jLabel10.setText("   DECONNECTER");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 190, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            
            
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String value = jComboBox1.getSelectedItem().toString();
        String n = jTextField1.getText();
       
            
            Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/buku", "root", "14400000");
                      myConn.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
            
            while(model.getRowCount()>0){
                 model.removeRow(0);
             }
            //2.create a statement

                   myStmt = myConn.createStatement();
        
                  
            
						 
			//3.Execute a sql query
                        if(value.equalsIgnoreCase("ISBN")){
                            
                            
                             myRs = myStmt.executeQuery(String.format("select ISBN, Cote, Titre, Auteur, Publication, Annee, Domain, Status from books where ISBN = '%s'", n));
                           
                             
                           /* if(!(myRs.next())){
                                JOptionPane.showMessageDialog(null, "Aucun Resultat!!", "", JOptionPane.INFORMATION_MESSAGE);
                             
                          /*   ResultSet  Rs = Stmt.executeQuery("select ISBN, Cote, Titre, Auteur, Publication, Annee, Domain, Status from books");
                  
                       
			
			//4.process the result set
			  while(Rs.next()) {
                              //affichage de la base de donnees dans le tableaux
                              model.insertRow(model.getRowCount(), new Object[]{Rs.getString("ISBN"), Rs.getString("Cote"), Rs.getString("Titre"), Rs.getString("Auteur"), Rs.getString("Publication"), Rs.getString("Annee"),Rs.getString("Domain"), Rs.getString("Status")});
				   /*System.out.println(myRs.getString("Id")+ " "+ myRs.getString("first_name") + " " + myRs.getString("last_name")+" "+ myRs.getString("email"));
				   
			   }
                             
                                
                          
                            }*/
                        }
                        else if(value.equalsIgnoreCase("Cote")){
                        myRs = myStmt.executeQuery(String.format("select ISBN, Cote, Titre, Auteur, Publication, Annee, Domain, Status from books where Cote = '%s'", n));
                       /* if(!(myRs.next())){
                                JOptionPane.showMessageDialog(null, "Aucun Resultat!!", "", JOptionPane.INFORMATION_MESSAGE);
                          
                            }*/
                        }
                        else if(value.equalsIgnoreCase("titre")){
                         myRs = myStmt.executeQuery(String.format("select ISBN, Cote, Titre, Auteur, Publication, Annee, Domain, Status from books where Titre = '%s'", n));
                         /*if(!(myRs.next())){
                                JOptionPane.showMessageDialog(null, "Aucun Resultat!!", "", JOptionPane.INFORMATION_MESSAGE);
                         
                            }*/
                        }
                        else if(value.equalsIgnoreCase("Auteur")){
                              myRs = myStmt.executeQuery(String.format("select ISBN, Cote, Titre, Auteur, Publication, Annee, Domain, Status from books where Auteur = '%s'", n));
                             /* if(!(myRs.next())){
                                JOptionPane.showMessageDialog(null, "Aucun Resultat!!", "", JOptionPane.INFORMATION_MESSAGE);
                            }*/
                             
                        }
                        else if(value.equalsIgnoreCase("Publication")){
                             myRs = myStmt.executeQuery(String.format("select ISBN, Cote, Titre, Auteur, Publication, Annee, Domain, Status from books where Publication = '%s'", n));
                             /*if(!(myRs.next())){
                                JOptionPane.showMessageDialog(null, "Aucun Resultat!!", "", JOptionPane.INFORMATION_MESSAGE);
                             
                           }*/
                             
                        }
                        else if(value.equalsIgnoreCase("Annee")){
                              myRs = myStmt.executeQuery(String.format("select ISBN, Cote, Titre, Auteur, Publication, Annee, Domain, Status from books where Annee = '%s'", n));
                            /* if(!(myRs.next())){
                                JOptionPane.showMessageDialog(null, "Aucun Resultat!!", "", JOptionPane.INFORMATION_MESSAGE);
                                
        
                            }*/
                             
                        }
                        else if(value.equalsIgnoreCase("Domaine")){
                            
                             myRs = myStmt.executeQuery(String.format("select ISBN, Cote, Titre, Auteur, Publication, Annee, Domain, Status from books where Domain = '%s'", n));
                            /*if(!(myRs.next())){
                                JOptionPane.showMessageDialog(null, "Aucun Resultat!!", "", JOptionPane.INFORMATION_MESSAGE);
                            
                            }*/
                        }
                        else{
                            
                            myRs = myStmt.executeQuery(String.format("select ISBN, Cote, Titre, Auteur, Publication, Annee, Domain, Status from books where Status = '%s'", n));
                            
                            /*if(!(myRs.next())){
                                JOptionPane.showMessageDialog(null, "Aucun Resultat!!", "", JOptionPane.INFORMATION_MESSAGE);
                           
                           }*/
                        }
                        
                        
                         
                         
                             
                             while(myRs.next()) {
                              
                              
                              
                                  model.insertRow(model.getRowCount(), new Object[]{myRs.getString("ISBN"), myRs.getString("Cote"), myRs.getString("Titre"), myRs.getString("Auteur"), myRs.getString("Publication"), myRs.getString("Annee"),myRs.getString("Domain"), myRs.getString("Status")});
                              
				   /*System.out.println(myRs.getString("Id")+ " "+ myRs.getString("first_name") + " " + myRs.getString("last_name")+" "+ myRs.getString("email"));*/
				 
                              }
                              
                              
                              //affichage be la base de donnees dans le tableaux
                                
			   
                         
                            
                        
                          
                        
                        
                  	   
            
                        
        }catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new UIaccueil().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        new nouveauLivre().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        new jobo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        new FormulaireInscription().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        new ImproveListe().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        new Registre().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new LogPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(repertoire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(repertoire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(repertoire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(repertoire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new repertoire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
